# Generated by Django 3.1.3 on 2020-12-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('sex', models.CharField(max_length=1, verbose_name='Sexo')),
                ('photo', models.ImageField(upload_to='user/avatar', verbose_name='Avatar')),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='User.Profile', verbose_name='Amigos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('scope', models.CharField(max_length=500, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criaçao')),
                ('deleted_at', models.DateTimeField(verbose_name='Deletado')),
                ('votes', models.IntegerField(default=0, verbose_name='Votos')),
                ('is_public', models.BooleanField(verbose_name='É publico?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile', verbose_name='Author')),
            ],
        ),
    ]
