# Generated by Django 3.1.3 on 2020-12-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nasc',
            field=models.DateField(blank=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user/avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, max_length=1, verbose_name='Sexo'),
        ),
    ]
