# Generated by Django 3.1.3 on 2020-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201211_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nasc',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_profile_friends_+', to='User.Profile', verbose_name='Amigos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
